### PR TITLE
cleanup while debugging

### PR DESCRIPTION
**Pull request by loechel**
#1

### CODE REVIEW

**Comment by Shriyanshagro** [comment]
Can you look into this again?
I'm getting following
`Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.importexport.browser.importexport, line 197, in export
  Module plone.importexport.browser.importexport, line 500, in getheaders
  Module plone.importexport.browser.importexport, line 112, in serialize
  Module plone.importexport.browser.importexport, line 98, in serialize
  Module plone.restapi.serializer.dxcontent, line 116, in __call__
  Module plone.restapi.serializer.dxcontent, line 77, in __call__
  Module plone.restapi.serializer.dxfields, line 24, in __call__
  Module plone.restapi.serializer.converters, line 34, in json_compatible
  Module zope.component.hookable, line 33, in __call__
  Module zope.component.hooks, line 104, in adapter_hook
  Module plone.restapi.serializer.converters, line 60, in list_converter
  Module plone.restapi.serializer.converters, line 34, in json_compatible
  Module zope.component.hookable, line 33, in __call__
  Module zope.component.hooks, line 104, in adapter_hook
  Module plone.restapi.serializer.relationfield, line 17, in relationvalue_converter
  Module plone.restapi.serializer.summary, line 31, in __call__
  Module plone.app.contentlisting.realobject, line 70, in review_state
  Module Products.CMFCore.WorkflowTool, line 263, in getInfoFor
WorkflowException: No workflow provides '${name}' information.
`
For a time being can you uncommit the changes for importexport.py? At the end of this product I by myself will do a code cleanup but for now, it does not look good to me.

**Comment by loechel** [comment]
Ok, I do see the problem, as the persons from the framework team did not accept the fix in plone.app.contentlisting with usage of plone.api, the return value is now Null, and no workflow state exists with this name. You have to explicite check for 'Null' input and translate that to the default state of this content type.

For the rest, it might be better, if you do a cherry pick of my changes in this branch, instead of merging this branch. I do not have the time to cleanup this branch for you.

**Comment by Shriyanshagro** [comment]
By default Files do not have a workflow state. So what in such case?

**Comment by loechel** [comment]
Well as you never know which workflow is active in your Plone Site you should lookup those, and if for a content type class no workflow is set, just ignore the transfered state.

**Comment by Shriyanshagro** [comment]
As far as I understand, there are some required checks for objects which have no defined review_state. 
So I believe that the required changes are to made on plone.restapi and not on plone.importexport? Am I right?

**Comment by loechel** [comment]
I would suggest to ask @frapell and @djay about that. But I think it will not be an element of plone.restapi to do it.

**Comment by frapell** [comment]
@loechel I didn't debug this, but looking at https://github.com/plone/plone.app.contentlisting/blob/master/plone/app/contentlisting/realobject.py#L87 it sounds like that review_state method should first check if the object has a workflow associated and return "None" if not. What do you think?

**Comment by loechel** [comment]
@frapell well that is not necessary. This method should be replaced by plone.api, and that never returns None, it returns a default.

The problem was before that this method review_state did not have any default and raised an exception instead. I first injected plone.api and checked the review_state via api, which returns a default ('published') instead. That fix was denied by framework team members (see https://github.com/plone/plone.app.contentlisting/pull/22) so I changed it to something that worked without raising the exception. But now on Import it did not know this state, which is correct. So it should either create and leave in default workflow or update and leave in current workflow state.

**Comment by Shriyanshagro** [comment]
I tested the above changes, and here are its effects-
* It **solves the problem of exporting** related_items field successfully for every possible review_state.
* But it raised another potential problem, as now **importing related fields** throws below-mentioned error for every possible review_state - 
ERROR: `[{'field': 'relatedItems', 'message': u'Required input is missing.', 'error': RequiredMissing('')}]`

Data of related_items field exported from addon(which is used for import as well) - `[{"@type": "Folder", "review_state": "published", "description": "Just GSoC stuff", "title": "GsoC17_new folder"}, {"@type": "File", "review_state": null, "description": "", "title": "Felicity_cabs"}]`

**Comment by Shriyanshagro** [comment]
@loechel  can you please look into this issue. Ping me back if my last comment is not clear to you. [Here](https://pastebin.com/UYiJ3S0s) is the complete log of import file

**Comment by Shriyanshagro** [comment]
@frapell it seems like @loechel  has uncommitted his changes on plone.app.contentlistings which eventually brings us back to square one and thus reopened #1  along with unclosed #4

**Comment by loechel** [comment]
I will close this Pull request, as GSoC is finished and the work has been merged into https://github.com/collective/plone.importexport 

Continued work should happen there on feature branches, and a general cleanup should start from scratch on current master.

**Pull request closed without merging**
